[package]
name = "imapsync-parallel"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
tokio = { version = "1", features = ["full"] }
num_cpus = "1.13.1"
clap = { version = "4.0", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
